### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by tiagoarasilva** [klaussilveira/gitlist#629]
There were some missing files and folders (GitList and Vendors) :-)

**Comment by tiagoarasilva** [comment]
I'm using windows and now i have this as an error:

"Oops! An exception has been thrown during the rendering of a template ("Parameter "repo" for route "repository" must match "Railscasts\\-Sync|intelligentmirror|active_hash" ("Railscasts-Sync" given) to generate a corresponding URL.") in "index.twig" at line 16."

**Comment by garygreen** [comment]
This has been fixed in master, just not tagged yet. I would suggest to use master branch if on windows, for now.

**Comment by tiagoarasilva** [comment]
But how do I set that?

Muito Obrigado / Kind Regards,
Tiago A. Silva

Sent from my Phone




On Fri, Oct 16, 2015 at 9:08 AM -0700, "Gary Green" <notifications@github.com> wrote:
This has been fixed in master, just not tagged yet. I would suggest to use master branch if on windows, for now.

---

**Comment by garygreen** [comment]
Just download or clone the master branch. https://github.com/klaussilveira/gitlist/archive/master.zip

**Comment by garygreen** [comment]
You'll also need to `composer install` from inside the directory to bring down the Symphony and other required components.

**Comment by tiagoarasilva** [comment]
I've tried those steps and I'm still receiving the same error....

**Comment by eppjohnny** [comment]
Could you post your webserver error log files?
